#!/usr/bin/env node
/**
 * Fetch KanjiVG stroke-order SVG data for every kana in Unit 1 and emit
 * src/data/kanjivg.js — a static map of { char → [svgPathString, ...] }.
 *
 * KanjiVG is CC BY-SA 3.0: https://kanjivg.tagaini.net
 * Run once (or whenever new kana are added): node scripts/fetch-kanjivg.mjs
 */

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");

// Kana that need stroke data — every kana item in the curriculum must have an
// entry (the content contract hard-errors otherwise). Grows as units ship.
//   base 46 hiragana (Units 1-2) + 25 dakuten/handakuten (Unit 3)
//   + full katakana: vowels→n-row (Unit 4), h/m/y/r/w rows + ン (Unit 5),
//     and g/z/d/b/p dakuten+handakuten rows (Unit 6).
const HIRAGANA = "あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん";
const DAKUTEN = "がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ";
const KATAKANA = "アイウエオカキクケコサシスセソタチツテトナニヌネノ" + // Unit 4
  "ハヒフヘホマミムメモヤユヨラリルレロワヲン" +                       // Unit 5
  "ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ";                  // Unit 6
// Kanji — N5 set, grows as kanji units ship.
const KANJI = "一二三四五六七八九十" + // numbers (Unit 11)
  "日月火水木金土山川田" +              // days / nature (Unit 11)
  "人大小中上下" +                      // people / position (Unit 11)
  "何時分半午曜週年今毎" +              // time / calendar (Unit 13)
  "行来見出入食飲言聞読" +              // everyday verbs (Unit 14)
  "父母男女子学校生先友" +              // people / school (Unit 15)
  "百千万円右左前後外間" +              // numbers / money / position (Unit 17)
  "東西南北道駅店国本名" +              // compass / places (Unit 18)
  "書話立休買会待知作持" +              // more verbs (Unit 19)
  "高安新古多少長白気元" +              // adjectives / state (Unit 20)
  "目耳口手足雨電車私語";                // body / nature (Unit 21)
// N3 kanji — B1 draft set, grows as B1 kanji units ship (draft-and-park; not in UNITS).
const KANJI_N3 =
  "政府治民選挙経済税費産貿社議制権賛保法律判護察罪" + // politics/economy/law (Unit 67)
  "自然境環星池資源災害石素科技術験果効論識認確報情" + // nature/science/info (Unit 68)
  "健康態状症療筋肉骨臓圧検性格信頼慣精怒喜泣笑悩慢" + // health/body/emotion (Unit 69)
  "職就給料責任努成功失敗績教授卒専門講義訳連絡告招" + // work/education/comm (Unit 70)
  "現在未将過突変増減続展移量割均合計満比番位極限総" + // time/change/quantity (Unit 71)
  "米麦粉塩砂卵焼煮蒸冷熱汁甘辛酸香濃薄器飯弁菜材缶" + // food & cooking (Unit 72)
  "宅壁床窓畳棚掃除洗濯片付押引閉締抜掛布袋傘鏡針綿" + // home & living (Unit 73)
  "晴曇湿嵐雷霧森林岩泉谷丘犬猫鳥魚虫馬花草竹松種咲" + // weather/nature/animals (Unit 74)
  "顔頭首髪舌喉肩腕胸腹背肌歩走飛座触握涙汗振抱額揺" + // body & movement (Unit 75)
  "交空迎泊訪迷街域郊距離側角端横縦斜沿航輸駐遅越昇" + // travel/places/direction (Unit 76)
  "太細広狭厚硬柔若老幼賢偉貧富豊貴良険静清汚危鋭鈍";   // adjectives & qualities (Unit 77)
const kanaChars = (HIRAGANA + DAKUTEN + KATAKANA + KANJI + KANJI_N3).split("");

console.log(`Fetching KanjiVG data for ${kanaChars.length} characters: ${kanaChars.join(" ")}\n`);

const result = {};

for (const char of kanaChars) {
  const cp = char.codePointAt(0).toString(16).padStart(5, "0");
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${cp}.svg`;

  process.stdout.write(`  ${char} (${cp})  `);
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const svg = await res.text();

    // Extract path d= attributes in stroke order (id ends with -s1, -s2, ...)
    const paths = [];
    const re = /id="kvg:[^"]*-s\d+"[^>]*d="([^"]+)"/g;
    let m;
    while ((m = re.exec(svg)) !== null) paths.push(m[1]);

    if (paths.length === 0) throw new Error("no strokes found");
    result[char] = paths;
    console.log(`${paths.length} strokes`);
  } catch (err) {
    console.log(`ERROR: ${err.message}`);
  }
}

// Emit JS module
const lines = [
  "// Auto-generated by scripts/fetch-kanjivg.mjs — do not edit by hand.",
  "// KanjiVG CC BY-SA 3.0 https://kanjivg.tagaini.net",
  "// Stroke paths are in 109×109 SVG coordinate space.",
  "export const KANJIVG = {",
];
for (const [char, paths] of Object.entries(result)) {
  lines.push(`  "${char}": [`);
  for (const p of paths) lines.push(`    "${p}",`);
  lines.push(`  ],`);
}
lines.push("};");

const out = join(ROOT, "src", "data", "kanjivg.js");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`\nWrote ${out}`);
