#!/usr/bin/env node
/**
 * Fetch KanjiVG stroke-order SVG data for every kana in Unit 1 and emit
 * src/data/kanjivg.js — a static map of { char → [svgPathString, ...] }.
 *
 * KanjiVG is CC BY-SA 3.0: https://kanjivg.tagaini.net
 * Run once (or whenever new kana are added): node scripts/fetch-kanjivg.mjs
 */

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");

// Kana that need stroke data — every kana item in the curriculum must have an
// entry (the content contract hard-errors otherwise). Grows as units ship.
//   base 46 hiragana (Units 1-2) + 25 dakuten/handakuten (Unit 3)
//   + full katakana: vowels→n-row (Unit 4), h/m/y/r/w rows + ン (Unit 5),
//     and g/z/d/b/p dakuten+handakuten rows (Unit 6).
const HIRAGANA = "あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん";
const DAKUTEN = "がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ";
const KATAKANA = "アイウエオカキクケコサシスセソタチツテトナニヌネノ" + // Unit 4
  "ハヒフヘホマミムメモヤユヨラリルレロワヲン" +                       // Unit 5
  "ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ";                  // Unit 6
// Kanji — N5 set, grows as kanji units ship.
const KANJI = "一二三四五六七八九十" + // numbers (Unit 11)
  "日月火水木金土山川田" +              // days / nature (Unit 11)
  "人大小中上下" +                      // people / position (Unit 11)
  "何時分半午曜週年今毎" +              // time / calendar (Unit 13)
  "行来見出入食飲言聞読" +              // everyday verbs (Unit 14)
  "父母男女子学校生先友" +              // people / school (Unit 15)
  "百千万円右左前後外間" +              // numbers / money / position (Unit 17)
  "東西南北道駅店国本名" +              // compass / places (Unit 18)
  "書話立休買会待知作持" +              // more verbs (Unit 19)
  "高安新古多少長白気元" +              // adjectives / state (Unit 20)
  "目耳口手足雨電車私語";                // body / nature (Unit 21)
// N4 kanji (A2) — fetched ahead of the A2 kanji units so stroke data is ready to
// author against. ~193 new glyphs (deduped against the N5 set above). Unused entries
// are harmless — the contract only requires kanji ITEMS to have strokes, not vice versa.
const KANJI_N4 =
  "悪暗医意育員院運泳央屋温化荷界開階寒感漢館岸起期客究急級宮球去橋業曲局銀区苦具君係軽血決研県庫湖" +
  "向幸港号根祭皿仕死使始指歯詩次事式実写者主守取酒受州拾終習集住重宿所暑助昭消商章勝乗植申身神真深" +
  "進世整昔全相送想息速族他打対代第題炭短談着注柱丁帳調追定庭笛鉄転都度投豆島湯登等動童農波配倍箱畑" +
  "発反坂板皮悲美鼻筆氷表秒病品負部服福物平返勉放味命面問役薬由油有遊予羊洋葉陽様落流旅両緑礼列練路和" +
  "通";
const kanaChars = (HIRAGANA + DAKUTEN + KATAKANA + KANJI + KANJI_N4).split("");

console.log(`Fetching KanjiVG data for ${kanaChars.length} characters: ${kanaChars.join(" ")}\n`);

const result = {};

for (const char of kanaChars) {
  const cp = char.codePointAt(0).toString(16).padStart(5, "0");
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${cp}.svg`;

  process.stdout.write(`  ${char} (${cp})  `);
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const svg = await res.text();

    // Extract path d= attributes in stroke order (id ends with -s1, -s2, ...)
    const paths = [];
    const re = /id="kvg:[^"]*-s\d+"[^>]*d="([^"]+)"/g;
    let m;
    while ((m = re.exec(svg)) !== null) paths.push(m[1]);

    if (paths.length === 0) throw new Error("no strokes found");
    result[char] = paths;
    console.log(`${paths.length} strokes`);
  } catch (err) {
    console.log(`ERROR: ${err.message}`);
  }
}

// Emit JS module
const lines = [
  "// Auto-generated by scripts/fetch-kanjivg.mjs — do not edit by hand.",
  "// KanjiVG CC BY-SA 3.0 https://kanjivg.tagaini.net",
  "// Stroke paths are in 109×109 SVG coordinate space.",
  "export const KANJIVG = {",
];
for (const [char, paths] of Object.entries(result)) {
  lines.push(`  "${char}": [`);
  for (const p of paths) lines.push(`    "${p}",`);
  lines.push(`  ],`);
}
lines.push("};");

const out = join(ROOT, "src", "data", "kanjivg.js");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`\nWrote ${out}`);
