#!/usr/bin/env node
/**
 * Fetch KanjiVG stroke-order SVG data for every kana in Unit 1 and emit
 * src/data/kanjivg.js — a static map of { char → [svgPathString, ...] }.
 *
 * KanjiVG is CC BY-SA 3.0: https://kanjivg.tagaini.net
 * Run once (or whenever new kana are added): node scripts/fetch-kanjivg.mjs
 */

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");

// Kana that need stroke data — every kana item in the curriculum must have an
// entry (the content contract hard-errors otherwise). Grows as units ship.
//   base 46 hiragana (Units 1-2) + 25 dakuten/handakuten (Unit 3)
//   + full katakana: vowels→n-row (Unit 4), h/m/y/r/w rows + ン (Unit 5),
//     and g/z/d/b/p dakuten+handakuten rows (Unit 6).
const HIRAGANA = "あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん";
const DAKUTEN = "がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ";
const KATAKANA = "アイウエオカキクケコサシスセソタチツテトナニヌネノ" + // Unit 4
  "ハヒフヘホマミムメモヤユヨラリルレロワヲン" +                       // Unit 5
  "ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ";                  // Unit 6
// Kanji — N5 set, grows as kanji units ship.
const KANJI = "一二三四五六七八九十" + // numbers (Unit 11)
  "日月火水木金土山川田天" +            // days / nature (Unit 11, 13)
  "人大小中上下" +                      // people / position (Unit 11)
  "何時分半午曜週年今毎" +              // time / calendar (Unit 13)
  "行来見出入食飲言聞読" +              // everyday verbs (Unit 14)
  "父母男女子学校生先友" +              // people / school (Unit 15)
  "百千万円右左前後外間" +              // numbers / money / position (Unit 17)
  "東西南北道駅店国本名" +              // compass / places (Unit 18)
  "書話立休買会待知作持" +              // more verbs (Unit 19)
  "高安新古多少長白気元" +              // adjectives / state (Unit 20)
  "目耳口手足雨電車私語" +               // body / nature (Unit 21)
  // --- N4 kanji (Units 31–42), 141 new glyphs ---
  "者自家主親族兄弟姉妹世代" +           // family (U31)
  "体医病死心力味" +                     // body / health (U32)
  "発動開通使集送起着運" +               // action verbs 1 (U33)
  "始終止切転走歩帰住去" +               // action verbs 2 (U34)
  "問答思意題考教習研究試験" +           // study & thought (U35)
  "字文漢英図音歌写映注画紙" +           // writing, arts & sound (U36)
  "売借貸品料計質銀仕業工建勉事員" +     // work & commerce (U37)
  "春夏秋冬昼夜朝夕花海空風" +           // nature & seasons (U38)
  "社地場京院界町館屋堂室台野" +         // places & buildings (U39)
  "赤青黒色明肉飯茶牛魚鳥犬" +           // colors & food (U40)
  "同正不無有特別物強広早急重楽悪" +     // descriptive (U41)
  "度用以近方理公洋服旅真";              // function & misc (U42)
const kanaChars = (HIRAGANA + DAKUTEN + KATAKANA + KANJI).split("");

console.log(`Fetching KanjiVG data for ${kanaChars.length} characters: ${kanaChars.join(" ")}\n`);

const result = {};

for (const char of kanaChars) {
  const cp = char.codePointAt(0).toString(16).padStart(5, "0");
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${cp}.svg`;

  process.stdout.write(`  ${char} (${cp})  `);
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const svg = await res.text();

    // Extract path d= attributes in stroke order (id ends with -s1, -s2, ...)
    const paths = [];
    const re = /id="kvg:[^"]*-s\d+"[^>]*d="([^"]+)"/g;
    let m;
    while ((m = re.exec(svg)) !== null) paths.push(m[1]);

    if (paths.length === 0) throw new Error("no strokes found");
    result[char] = paths;
    console.log(`${paths.length} strokes`);
  } catch (err) {
    console.log(`ERROR: ${err.message}`);
  }
}

// Emit JS module
const lines = [
  "// Auto-generated by scripts/fetch-kanjivg.mjs — do not edit by hand.",
  "// KanjiVG CC BY-SA 3.0 https://kanjivg.tagaini.net",
  "// Stroke paths are in 109×109 SVG coordinate space.",
  "export const KANJIVG = {",
];
for (const [char, paths] of Object.entries(result)) {
  lines.push(`  "${char}": [`);
  for (const p of paths) lines.push(`    "${p}",`);
  lines.push(`  ],`);
}
lines.push("};");

const out = join(ROOT, "src", "data", "kanjivg.js");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`\nWrote ${out}`);
